--- # Share Runtime Configuration

# This file contains runtime configuration shared between all platforms.
# This file is used to generate www/build-vars.js and is accessible at runtime
# via the Configuration service: this.Configuration.buildVars.config.appName
# Variables will be subsituted based on the active build scheme in schemes.yml.

appName: "${APP_NAME}"
appDescription: "${APP_DESCRIPTION}"
appVersion: "${APP_VERSION}"

authorName: "${AUTHOR_NAME}"
authorEmail: "${AUTHOR_EMAIL}"
authorWebsite: "${AUTHOR_WEBSITE}"

licenseUrl: "https://github.com/Justin-Credible/the-week-magazine-unofficial/blob/master/LICENSE"
githubUrl: "https://github.com/Justin-Credible/the-week-magazine-unofficial"

# The base URL for the magazine content.
contentUrl: "${CONTENT_URL}"

# Indicates if this application was built to be served as a website.
isWebPlatform: ${IS_WEB_PLATFORM}
