--- # Build Schemes

# The name of the scheme to use if one isn't provided via the --scheme flag.
default: "development"

# This holds a collection of data that can be used to override and/or supplement existing
# scheme replacement collections. These values will stomp over values from a scheme when
# used. These can be used by appending the name on to an existing scheme with a comma.
# For Example: gulp config --scheme development,web
overrides:
    web:
        IS_WEB_PLATFORM: true

# Different build schemes used by "gulp config --scheme scheme_name".
# These are used to set the debug flag and perform variable replacement on other files.
schemes:
    # A common/base scheme for names, versions, etc.
    # Not to be used directly; should be used as a base for all other schemes.
    _common:
        replacements:
            APP_NAME: "The Week Magazine - Unofficial App"
            APP_DESCRIPTION: "An unofficial app for The Week magazine."
            APP_VERSION: "1.0.0"
            AUTHOR_NAME: "Justin Unterreiner"
            AUTHOR_EMAIL: "justin.unterreiner@gmail.com"
            AUTHOR_WEBSITE: "http://www.justin-credible.net"
            IS_WEB_PLATFORM: false

    # Used for development on a host entry pointing to localhost.
    development:
        base: "_common"
        debug: true
        replacements:
            CONTENT_URL: "https://home.justin-credible.net/private/the-week"

            # See: http://content-security-policy.com/
            # Allows connecting to Ionic serve's LiveReload service via port 35279 and unsafe-inline script block.
            CONTENT_SECURITY_POLICY:
                default_src:
                    - "'self'"
                    - "data:"
                    - "gap:"
                    - "https://ssl.gstatic.com"
                script_src:
                    - "*"
                    - "'unsafe-eval'"
                    - "'unsafe-inline'"
                style_src:
                    - "'self'"
                    - "'unsafe-inline'"
                img_src:
                    - "*"
                connect_src:
                    - "'self'"
                    - "https://home.justin-credible.net"
                    - "http://home.justin-credible.net"
                    - "https://*.theweek.com"
                    - "http://*.theweek.com"

                    # Allows connecting to Ionic serve's LiveReload service via port 35279.
                    - "ws://localhost:35279"
                    - "ws://localhost:35729"

    # Used for shipping release builds, points at production.
    release:
        base: "_common"
        debug: false
        replacements:
            CONTENT_URL: "https://magazine.theweek.com"
            
            # See: http://content-security-policy.com/
            CONTENT_SECURITY_POLICY:
                default_src:
                    - "'self'"
                    - "data:"
                    - "gap:"
                    - "https://ssl.gstatic.com"
                script_src:
                    - "*"
                    - "'unsafe-eval'"
                    - "'unsafe-inline'"
                style_src:
                    - "'self'"
                    - "'unsafe-inline'"
                img_src:
                    - "*"
                connect_src:
                    - "'self'"
                    - "https://*.theweek.com"
                    - "http://*.theweek.com"
